spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/studyspringboot?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  #1、上线时需要改变日志输出的位置
  redis:
    host: 127.0.0.1
    port: 6379
server:
  servlet:
    context-path: "/WxSpringboot"
#logging:
#  pattern:
#    console: "%d-%msg%n"
##  path: "F:\\LogInfo"
#  file: "F:\\LogInfo/file.log"
wechat:
  mpAppId: 1111111
  mpSecret: 11111111
  openAppId: 1111111
  openAppSecret: 11111
  mchId: adasdsd
  mchKey: xxxxxx
  #证书路径
  mkeyPath: aaa
  notifyUrl: http://www.xiingluote.cn/WxSpringboot/pay/noify

projecturl:
  sellerLoginSuccess: http://localhost:8080
  sellerExceptionUrl: http://localhost:8080

